#!/bin/bash
#PBS -l nodes=8:ppn=32:xe
#PBS -l walltime=00:20:00
#PBS -A jq7
#PBS -N nodecomm ### Name of job
#PBS -e nodecomm_contention_x_128_$PBS_JOBID.err  ### Error File
#PBS -o nodecomm_contention_x_128_$PBS_JOBID.out  ### Output File
#PBS -l geometry=4x1x1

export MPICH_RANK_REORDER_METHOD=1
cd "/u/sciteam/bienz/TopoModel/modeling/baseenv/haloperf"
aprun -n 128 -N 16 -d 2 ./nodecomm_contention_8


